### ISSUE TITLE
Error loading prompt at index 0

### ISSUE THREAD

**Issue by hongvvu** [byjlw/video-analyzer#8]
On Mac OS
after running `video-analyzer "path/to/myvideo.mp4" returns following error

```
2024-12-22 18:32:37,314 - INFO - Extracting audio from video...
2024-12-22 18:32:37,391 - INFO - Transcribing audio...
2024-12-22 18:32:37,420 - INFO - Processing audio with duration 00:15.581
2024-12-22 18:32:37,470 - INFO - VAD filter removed 00:05.597 of audio
2024-12-22 18:32:39,241 - INFO - Detected language 'zh' with probability 0.98
2024-12-22 18:34:28,192 - INFO - Extracting frames from video using model llama3.2-vision...
2024-12-22 18:34:28,296 - INFO - Extracted 15 frames from video (target was 15)
2024-12-22 18:34:28,296 - INFO - Analyzing frames...
2024-12-22 18:34:28,296 - ERROR - Error loading prompt at index 0: Prompt file not found in prompts/frame_analysis/frame_analysis.txt or package resources
2024-12-22 18:34:28,296 - ERROR - Error during video analysis: Prompt file not found in prompts/frame_analysis/frame_analysis.txt or package resources
```

**Comment by byjlw** [comment]
Did you install the project using `pip install .`  ?

That command will ensure things are in the right place. 
You can also look on disk to ensure you didn't remove the prompt files somehow. Prompts are in the directory `prompts/frame_analysis/` from the root

**Comment by byjlw** [comment]
no response and can't recreate so closing

**Comment by sorphwer** [comment]
Hi @hongvvu @byjlw  I just come up with same issue and fixed it.

The key is the current path where you run the command, which means, you have to execute analyzer command in `repos\video-analyzer\video_analyzer`  rather than the root path of the repo `repos\video-analyzer`, so the prompt folder can be successfully accessed.

**Comment by hongvvu** [comment]
@sorphwer yes, you are right, thank you so much, your solution works. happy new year!

**Comment by byjlw** [comment]
Good callout. I'll add fixing this to the list

**Comment by byjlw** [comment]
fixed with this PR
https://github.com/byjlw/video-analyzer/pull/14

**Comment by sorphwer** [comment]
@byjlw  Thanks for you works but I just got same issue after git pull, have you re-tested this after #14  ?

**Comment by byjlw** [comment]
can you provide the command you used (don't share your key if you're using a service) and the entire output. Please run the command with --log-level DEBUG so i can see the full output

**Comment by byjlw** [comment]
Are you still able to repro? If so can you share the logs?

**Comment by hongvvu** [comment]
re-installed with latest pull
still you have to run the command in the `video-analyzer` folder, otherwise you will have the `Error loading prompt at index 0:`
```
2025-01-07 11:54:18,999 - DEBUG - Using packaged default config from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/config/default_config.json
2025-01-07 11:54:18,999 - DEBUG - No user config found, loading default config from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/config/default_config.json
2025-01-07 11:54:18,999 - DEBUG - Initializing audio processing...
2025-01-07 11:54:19,172 - DEBUG - Using HuggingFace cache directory: /Users/hongwu/.cache/huggingface/hub
2025-01-07 11:54:19,172 - DEBUG - Using device: cpu
2025-01-07 11:54:19,180 - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2025-01-07 11:54:19,300 - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-medium/revision/main HTTP/1.1" 200 2080
2025-01-07 11:54:20,404 - DEBUG - Successfully loaded Whisper model: medium
2025-01-07 11:54:20,500 - INFO - Extracting audio from video...
2025-01-07 11:54:20,590 - DEBUG - Successfully extracted audio using ffmpeg
2025-01-07 11:54:20,590 - INFO - Transcribing audio...
2025-01-07 11:54:20,620 - INFO - Processing audio with duration 00:26.099
2025-01-07 11:54:20,686 - INFO - VAD filter removed 00:20.787 of audio
2025-01-07 11:54:20,686 - DEBUG - VAD filter kept the following audio segments: [00:11.216 -> 00:16.528]
2025-01-07 11:54:22,301 - INFO - Detected language 'ko' with probability 0.46
2025-01-07 11:54:22,303 - DEBUG - Processing segment at 00:00.000
2025-01-07 11:54:30,029 - DEBUG - Compression ratio threshold is not met with temperature 0.0 (3.851852 > 2.400000)
2025-01-07 11:54:31,557 - DEBUG - Log probability threshold is not met with temperature 0.2 (-1.943265 < -1.000000)
2025-01-07 11:54:31,557 - DEBUG - No speech threshold is met (0.779253 > 0.600000)
2025-01-07 11:54:31,557 - WARNING - No speech detected in audio
2025-01-07 11:54:31,557 - WARNING - Could not generate reliable transcript. Proceeding with video analysis only.
2025-01-07 11:54:31,557 - INFO - Extracting frames from video using model llama3.2-vision...
2025-01-07 11:54:31,728 - INFO - Extracted 25 frames from video (target was 25)
2025-01-07 11:54:31,733 - INFO - Analyzing frames...
2025-01-07 11:54:31,733 - ERROR - Error loading prompt at index 0: Prompt file not found in prompts/frame_analysis/frame_analysis.txt or package resources
2025-01-07 11:54:31,733 - ERROR - Error during video analysis: Prompt file not found in prompts/frame_analysis/frame_analysis.txt or package resources
2025-01-07 11:54:31,734 - DEBUG - Cleaned up frames directory: output/frames
2025-01-07 11:54:31,734 - DEBUG - Cleaned up audio file: output/audio.wav
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/video-analyzer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/cli.py", line 144, in main
    analyzer = VideoAnalyzer(client, model, prompt_loader, config.get("prompt", ""))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/analyzer.py", line 25, in __init__
    self._load_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/analyzer.py", line 36, in _load_prompts
    self.frame_prompt = self.prompt_loader.get_by_index(0)  # Frame Analysis prompt
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/prompt.py", line 49, in get_by_index
    prompt_path = self._find_prompt_file(prompt["path"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/video_analyzer/prompt.py", line 29, in _find_prompt_file
    raise FileNotFoundError(f"Prompt file not found in {user_path} or package resources")
FileNotFoundError: Prompt file not found in prompts/frame_analysis/frame_analysis.txt or package resources
```

**Comment by byjlw** [comment]
Hmmm I still haven't been able to repro but I have an idea. 

If you update your config file to specify the absolute path to the prompts do things work? 

If you could share the exact commands you run to install (including any sort of environment creating such as venv or conda) as well as the exact directory you're running the video-analyzer command from I'll see if I can repro following your exact steps

**Comment by byjlw** [comment]
does this work? 
https://github.com/byjlw/video-analyzer/issues/22#issuecomment-2581732544

**Comment by byjlw** [comment]
Ok i think this PR should fix it

https://github.com/byjlw/video-analyzer/pull/23

**Comment by hongvvu** [comment]
Yes, awesome! no issue after running same command after pulling #23 . Thanks for the fix

**Comment by byjlw** [comment]
Fixed by PR #23
